# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e090eba989dbb877360e64f475f9c766c7f775421a22d584b4a1e653fc80faf81f8576f2249433c6a0670d81a2d5969300451cadb63d6c37199674f3c9750bf

test:
  secret_key_base: f793b747c58a77c09a67d2566c4731ef380051e564c85eb71058adb773f29befc8a97cb82476960cb83a1c362ecdda78b63e7024978d3712a41f554cab1bf9d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
